name = "QuickTemplates"
uuid = "e0a1e0cf-adbd-4af0-bae4-f392a3de8ba5"
version = "0.10.1"
authors = ["Sim√≥n Gonzalez"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Dates = "1"
Mustache = "1"
TOML = "1"
UUIDs = "1"
julia = "1.12"
